# Generated by Django 3.1.7 on 2021-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
            ],
        ),
    ]
